#!/usr/bin/env python
# encoding: utf-8
"""
Interface to list of stars and fields from CAS

This uses a mongodb database generated by the populate_cas_db.py script

History
-------
2011-06-13 - Created by Dan Foreman-Mackey

"""

__all__ = ['']

import numpy as np

import pymongo

from opt import *

# connect to mongodb
_db = pymongo.Connection()[casdb]
_stardb  = _db[casstars]
_fielddb = _db[casfields]

def _angular_distance(ra1,dec1,ra2,dec2):
    """
    Calculate the angular separation of 2 objects in RA/Dec space
    
    Parameters
    ----------
    ra1 : float
        In degrees
    
    dec1 : float
        In degrees
    
    ra2 : float
        In degrees
    
    dec2 : float
        In degrees
    
    Returns
    -------
    rho : float
        In degrees
    
    History
    -------
    2011-06-13 - Created by Dan Foreman-Mackey
    
    """
    ra1,dec1 = np.radians(ra1),np.radians(dec1)
    ra2,dec2 = np.radians(ra2),np.radians(dec2)
    crho = np.cos(dec1)*np.cos(dec2)\
            *(np.cos(ra1)*np.cos(ra2)+np.sin(dec1)*np.sin(dec2))\
            +np.sin(dec1)*np.sin(dec2)
    return np.degrees(np.arccos(crho))
